### PR TITLE
add explanation to README for why this exists

### PR DESCRIPTION
**Pull request by celeduc**
Resolves issue #6

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Actually, with the release of 0.4.5 you can now create new keys and publish them with `ipfs publish -k`.

Its probably time to deprecate this repo now.

**Comment by whyrusleeping** [comment]
That said, thank you for the PR and your interest in making the project better :)

**Comment by celeduc** [comment]
then I look forward to the release of IPFS 0.4.5 :smile:

**Comment by celeduc** [comment]
Oh look, it happened. https://dist.ipfs.io/#go-ipfs

**Pull request closed without merging**
